Time: 06-07-2025 11:14:12
model: VGG16
parameters: 134276034
dir: training/VGG16_crossentropy_adamw_onecycle
num_epochs: 200
run_epoch: 200
learning_rate: 0.001
optimizer_name: adamw
loss_name: crossentropy
scheduler: Onecycle
early_stopping_patience: 10
early_stopping_delta: 0.001
best_loss: 0.11385087377425097
batch_size: 16
train_images: 4809
valid_images: 1030
image_shape: torch.Size([1, 224, 224])
device: cuda:0
transform_image: True
loss: CrossEntropy
optimizer: Adamw
dataset: ROI_enhance
