Time: 09-07-2025 02:52:06
model: ResNet50
parameters: 23505858
dir: training_seg/ResNet50_crossentropy_adam_reducelronplateau
num_epochs: 100
run_epoch: 212
learning_rate: 0.01
optimizer_name: adam
loss_name: crossentropy
scheduler: ReduceLROnPlateau
early_stopping_patience: 10
early_stopping_delta: 0.001
best_loss: 0.2343681595857861
batch_size: 16
train_images: 4809
valid_images: 1030
image_shape: torch.Size([1, 224, 224])
device: cuda:0
transform_image: True
loss: CrossEntropy
optimizer: Adam
dataset: seg_enhance
lr: 0.01
