Time: 06-07-2025 08:46:28
model: ResNet50
parameters: 23505858
dir: training/ResNet50_focal_adam_onecycle
num_epochs: 100
run_epoch: 200
learning_rate: 0.001
optimizer_name: adam
loss_name: focal
scheduler: Onecycle
early_stopping_patience: 10
early_stopping_delta: 0.001
best_loss: 0.0330418392755905
batch_size: 16
train_images: 4809
valid_images: 1030
image_shape: torch.Size([1, 224, 224])
device: cuda:0
transform_image: True
loss: Focal
optimizer: Adam
dataset: ROI_enhance
