Time: 09-07-2025 16:59:01
model: ResNet50
parameters: 23505858
dir: training_seg/ResNet50_crossentropy_adamw_reducelronplateau
num_epochs: 200
run_epoch: 200
learning_rate: 0.01
optimizer_name: adamw
loss_name: crossentropy
scheduler: ReduceLROnPlateau
early_stopping_patience: 10
early_stopping_delta: 0.001
best_loss: 0.14753979070799297
batch_size: 16
train_images: 4809
valid_images: 1030
image_shape: torch.Size([1, 224, 224])
device: cuda:1
transform_image: True
loss: CrossEntropy
optimizer: Adamw
dataset: seg_enhance
lr: 0.01
